base_url = "https://Onmyputer.com"
title = "Onmyputer"
description = "Ian Le's Personal Page"

compile_sass = true

taxonomies = [
    { name = "tags" },
    { name = "categories" },
    { name = "contexts" },
]

#[markdown]
#highlight_code = true

[extra]
author = "Ian Le"
model = ""
logo = "images/logo.png"
header_nav = [
    { name = "Home", url = "/" },
    { name = "Projects", url = "/projects" },
    { name = "Hobbies", url = "/hobbies" },
    { name = "Recipes", url = "/recipes" },
    { name = "Friends", url = "https://sbcord.com" },
#    { name = "!Resume", url = "" },
#    { name = "?about", url = "/about" },
]