base_url = "https://onmyputer.com"
title = "Onmyputer"
description = "Ian Le's Personal Page"

compile_sass = true

taxonomies = [
    { name = "tags" },
    { name = "categories" },
    { name = "contexts" },
]

[markdown]
highlight_code = true

[extra]
author = "Ian Le"
logo = "images/logo.png"
header_nav = [
    { name = "~home", url = "/" },
    { name = "#projects", url = "/projects" },
    { name = "$hobbies", url = "/hobbies" },
#    { name = "?about", url = "/about" },
]